---
abstract: 'create OPML using XML::Simple'
author:
  - 'Marcus Theisen <marcus@thiesen.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-OPML-SimpleGen
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  XML::OPML::SimpleGen:
    file: lib/XML/OPML/SimpleGen.pm
    version: 0.040_002
requires:
  Class::Accessor: 0
  POSIX: 0
  XML::Simple: 0
  base: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=XML-OPML-SimpleGen
version: 0.040_002
